---
dependencies: []

galaxy_info:
  author: melwyn
  description: "Repositores for CentOS 7"
  company: "DTU"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - packaging
    - epel
    - repository
    - repo
